version: '3.9'
services:
  jenkins:
    build: 
      context: .
    container_name: 'jenkins-mc'
    ports:
      - '80:8080'
      - '50000:50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
